# Generated by Django 3.1.1 on 2021-02-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210215_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_product',
            name='car_type',
        ),
    ]
