# Generated by Django 3.1.1 on 2021-03-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_seller_product_car_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller_product',
            options={'verbose_name_plural': 'Seller_Product'},
        ),
        migrations.AddField(
            model_name='seller_product',
            name='approve',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
