# Generated by Django 3.1.1 on 2021-05-21 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210316_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='car_name',
            field=models.CharField(choices=[('Range Rover', 'Range Rover'), ('Land Rover Range Rover', 'Land Rover Range Rover'), ('Mercedes Benz', 'Mercedes Benz'), ('Toyota', 'Toyota'), ('Lexus', 'Lexus'), ('Rolls Royce', 'Rolls Royce'), ('', 'Car Name')], default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='car_owner_location',
            field=models.CharField(choices=[('Ikeja', 'Ikeja'), ('Oshodi', 'Oshodi'), ('Lekki', 'Lekki'), ('Festac', 'Festac'), ('Apapa', 'Apapa'), ('Surulere', 'Surulere'), ('', 'Car Type')], default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='car_price',
            field=models.DecimalField(choices=[('200000', '200000'), ('900000', '900000'), ('1000000', '1000000'), ('1300000', '1300000'), ('2300000', '2300000'), ('45000000', '45000000'), ('11800000', '11800000'), ('260000000', '260000000'), ('15000000', '15000000'), ('4000000', '4000000'), ('23500000', '23500000'), ('26000000', '26000000'), ('3200000', '3200000'), ('24500000', '24500000'), ('70000000', '70000000'), ('', 'Price')], decimal_places=2, default='', max_digits=12),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='category',
            field=models.ForeignKey(choices=[('Foreign', 'Foreign'), ('Local', 'Local'), ('', 'Car Type')], default='', on_delete=django.db.models.deletion.CASCADE, to='frontend.category'),
        ),
    ]
