# Generated by Django 3.1.1 on 2021-05-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20210521_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.category'),
        ),
    ]
