# Generated by Django 3.1.1 on 2021-05-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20210521_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='car_owner_location',
            field=models.CharField(choices=[('Ikeja', 'Ikeja'), ('Oshodi', 'Oshodi'), ('Lekki', 'Lekki'), ('Festac', 'Festac'), ('Apapa', 'Apapa'), ('Surulere', 'Surulere'), ('', 'Car Location')], default='', max_length=80),
        ),
    ]
